### ISSUE TITLE
Vario freeze on high volume

### ISSUE THREAD

**Issue by fhorinek** [fhorinek/BB#5] opened 2021-07-12 06:11 UTC
When I set audio sound to 95% and enable vario sound, device has frozen and cannot be started, cannot be reseted. Only when I connect power adapter for a second then I am able to start vario again. Too big power consumption?

**Comment by fhorinek** [comment] 2021-07-20 11:03
It is caused by the battery protection circuit.
The volume control is directly fed to amplifier register.
We need to limit the maximum volume anyway to protect the speaker

**Comment by tomasz13** [comment] 2021-10-04 07:56
the issue is closed, because in the FWBuild 138 may be a fix for this, but I found the same issue in  FW-D0000166 

I have set 100% volume in the Bluetooth menu & after some peeps the device has frozen and cannot be started, cannot be reseted. Only when I connect power adapter for a second then I am able to start vario again.
please check it and fix it again ;)

**Closed** 2022-10-10 06:15 UTC
Labels: bug
