### ISSUE TITLE
Fw207 Bus Fault when switching on

### ISSUE THREAD

**Issue by ashghinn** [fhorinek/BB#138] opened 2021-12-20 23:12 UTC
Updated to 207 successfully earlier, but now I can't switch it on. It repeatedly shows fault screen.
![16400418572781686109478839402305](https://user-images.githubusercontent.com/87761815/146844781-c7842870-87d6-42a2-b9a6-274569d2906a.jpg)

**Comment by ashghinn** [comment] 2021-12-20 23:34
I first encountered this problem after I had added a page, placed the new Thermal Assist widget on that new page and set the page to automatically enable when thermaling is detected. After reinstalling FW 207 it started normally, but the bus fault reappeared if I switched it off and tried to reboot. 

By reinstalling the firmware again, I got to the page menu and delete the page I'd created earlier today. Having done that I can now boot up without the fault page appearing. Hope this helps!

**Comment by fhorinek** [comment] 2021-12-21 08:58
so now you can't use thermal assistant? It will crash if you add the widget and boot up? can you send me the config folder to fero@skybean.eu. I am not able to reproduce it from the description Thank you

**Comment by fliescher** [comment] 2021-12-21 09:44
I was able to reproduce it in a way. For me BFAR, R1 and R2 differe from @ashghinn 's:
BFAR: FFFFFF1E
R1: 0xFFFFFF22
R2: 0x0000000
Maybe it helps.

In my case I placed the Thermal assistant with some other (older) widgets on the second page and old widgets (vario, g-Force, speed, height,...) on the first page.
I set the auto switching to circling for page 2 and enabled all other auto-switching possibilities for page 1.

By editing the default.cfg in Strato/ config/profiles/default.cfg (erase the values of page_power to page_land) I was able to restore the device again without reinstalling the fw-file

**Comment by ashghinn** [comment] 2021-12-21 12:13
> 
![temp](https://user-images.githubusercontent.com/87761815/146928084-9a37f884-3a35-495f-b532-1ae99b850dbf.jpg)

The fault has reoccurred when I switched on my Strato this morning. Here's the latest Bus Fault display (slightly different to the previous one). I've sent a copy of my current config folder to fero@skybean.eu as requested.

**Comment by fhorinek** [comment] 2021-12-21 12:31
Thank you for the file, this bug is number one priority to me. I hope I can fix it to the end of this day.

**Comment by ukeconsulting** [comment] 2021-12-22 20:01
i got the same screen twice when thermaling with thermal assistance (FW207)

**Comment by fhorinek** [comment] 2021-12-22 21:46
Please try 208, the problem was race condition when reusing statically allocated animation handle and the respective callback

**Comment by ukeconsulting** [comment] 2021-12-22 22:56
wifi update 207 to 208 : error : update file not valid.
manual update: first run nothing no update, second run ok.
is there a delay before running the update? 

i will test the 208 in flight tomorrow

**Comment by fhorinek** [comment] 2021-12-23 00:56
There should be no delay
can you send me the downloaded firmware file from your strato system/fw/D000207.fw to fero@skybean.eu
I would like to see the file corruption during the wifi download

**Comment by ukeconsulting** [comment] 2021-12-23 10:46
sorry i already replaced the bad 207 with the good one on the vario. 
 and upgrading from 207 to 208 with wifi on the second strato went just with problem with wifi deconnection like before, no "error : update file not valid"
 
 40km/h wind i can't test live the 208 today, tomorrow i hope.

**Comment by fhorinek** [comment] 2021-12-27 08:20
This issue is fixed in 208

**Closed by fhorinek** 2021-12-27 08:20 UTC

**Comment by ukeconsulting** [comment] 2022-01-04 13:43
i confirm: after several test flights, no more bus fault. 
sorry for the late notice, i had no good weather and after no internet :-/

**Comment by fhorinek** [comment] 2022-01-04 18:40
Thank you for the report
