### ISSUE TITLE
[FW261 - release] Frozen every few minutes

### ISSUE THREAD

**Issue by vojtechBohman** [fhorinek/BB#272] opened 2022-04-19 15:59 UTC
Based on your flyer's note that you have a stable release where everything works, I have used the vario while flying in Bassano.

I had both bluetooth and wifi turned off. Only the flarm was on because that's why I bought it.

During each flight the vario froze periodically maybe every 20-30 minutes when the bus fault message came up.

It also used to happen that the vario would start making a regular climbing or descending sound, and it wouldn't do anything else until the device was reset.

So how is it with your stable software? Do you have any or is this just planned marketing talk?

I'm very happy to use the Samsung Note as my main one with the XCtrack app which is free. I must say it works top notch and offers great navigation, thermall assistent and live possition sharing capabilities. The only advantage of your product is the more responsive vario and FLARM. Even your maps are woefully useless and slow.  

[crash_report.zip](https://github.com/fhorinek/BB/files/8514552/crash_report.zip)  
[crash_report_1.zip](https://github.com/fhorinek/BB/files/8514529/crash_report_1.zip)    
[crash_report_2.zip](https://github.com/fhorinek/BB/files/8514533/crash_report_2.zip)  
[crash_report_3.zip](https://github.com/fhorinek/BB/files/8514538/crash_report_3.zip)  
[crash_report_4.zip](https://github.com/fhorinek/BB/files/8514542/crash_report_4.zip)  

[debug.log](https://github.com/fhorinek/BB/files/8514555/debug.log)  
![obrazek](https://user-images.githubusercontent.com/82414966/164045638-e6a9d23e-2d3e-40a5-b789-89b9c1082646.png)

**Comment by BoehniM** [comment] 2022-04-20 06:03
Others work decently- like mine - but I agree with you, they have to push forward and explain why some work properly and others don’t - and generally give us more information about the next steps. The last announcements of fortnight-steps are obviously obsolete.

**Comment by fhorinek** [comment] 2022-04-21 22:01
I have inspected all your crash reports. It was not obvious, since every crash reason was different. The root cause was the maximum fanet users in the area. The user limit was not enforced and it cause unexpected memory overwrites. The patched firmware is released as R262.

**Comment by fhorinek** [comment] 2022-04-21 22:13
> Others work decently- like mine - but I agree with you, they have to push forward and explain why some work properly and others don’t - and generally give us more information about the next steps. The last announcements of fortnight-steps are obviously obsolete.

Currently we are focused on stability, we are solving more exotic failure modes that we ware not able to simulate yourself. This is good example since we have never tested strato with 70+ fanet devices. 

We have implemented the crash report system with automatic upload for processing and statistics recently. This bug would be very hard to find without this system in place.

Another big and unpredictable problem is with the filesystem on sd card. The fatfs is prone to corruption, but we are unable to fix it (or even detect on the embedded device reliably). Strato is also using it much more than the SkyDrop for example. The problems are mostly hidden but the corrupted filesystem structure might cause the audio profile load to fail, break IGC log or cause crash. So on going development is now to replace it with file system resistant to corruption(littlefs) and different usb protocol (MTP) since this filesystem is not readable via mass storage.

New features are now on hold.

**Closed by fhorinek** 2022-04-21 22:13 UTC
