### ISSUE TITLE
Bluetooth LE connection doesnt work - Android 5

### ISSUE THREAD

**Issue by vojtechBohman** [fhorinek/BB#116] opened 2021-10-25 16:04 UTC
I wanted to try different device to test the data transmission to XCtrack.
Phone: Samsung Note 3, android 5  

I am able to connect to Stato a2dp audio but not to the LE.  
- Phone connects to Strato
- then the screen to write PIN is shown on phone
- but PIN code stored in Strato setting is not valid and phone disconnects from the Strato
## Strato settings
![cfg](https://user-images.githubusercontent.com/82414966/138730269-08a06a72-92e9-45fa-952a-57221fb9c33d.jpg)
## Connected
![connect](https://user-images.githubusercontent.com/82414966/138730289-f4ad2039-1c90-4ae1-a387-85ec89905f3c.jpg)
## Disconected
![disconnect](https://user-images.githubusercontent.com/82414966/138730296-e154fc61-4302-43d5-bfa3-5e3b3592c334.jpg)

**Comment by vojtechBohman** [comment] 2021-11-03 07:33
I will share it during weekend. Did not have a time so far.

**Comment by vojtechBohman** [comment] 2021-11-05 11:56
I tried to connect to Strato LE directly from XcTrack - the same behavior. Request was tried 3 times.  
[debug.log](https://github.com/fhorinek/BB/files/7485783/debug.log)

Could you add command to Clear/Delete Debug file directly from Strato (Dev menu)? It would be easier to record.

**Comment by vojtechBohman** [comment] 2021-11-17 18:43
With the FW 177, data GNSS data are transferred for a short time, but when the psw message is show, the connection is lost.

**Comment by fhorinek** [comment] 2021-11-17 19:26
I will make an option to not secure the connection (no password request) for you to try.

**Comment by Tokter** [comment] 2021-12-20 21:16
Using a Google Pixel 4XL phone with Android 12. I'm having the same problem. I can connect the bluetooth to play audio. But when I try to connect via BLE:
- the Strato shows connected
- my phone prompts me for the pin
- no matter if I enter the pin, or cancel it, the Strato shows disconnected shortly after.

Here's my log:
[debug.log](https://github.com/fhorinek/BB/files/7747989/debug.log)

**Comment by fhorinek** [comment] 2021-12-20 22:54
@Tokter can you try build 207

**Comment by Tokter** [comment] 2021-12-20 23:22
I'm on 207:

One thing that I noticed is, that the connection message says:
60:e9:ba:a6:d5:ff connected (BLE)
![image](https://user-images.githubusercontent.com/3439101/146845453-8d998544-cc80-41a8-aa71-987a93877a67.png)

But on disconnect it says: e9:ba:a6:d5:ff:16 disconnected (BLE)
![image](https://user-images.githubusercontent.com/3439101/146845493-827ec797-6725-4fce-9d25-de471fd9986c.png)

So it looks like the ID got shifted to the left, not sure if that is of relevance..

```
 --------------- 20.12.2021 | 16:04.58 ---------------
[324][System][I] SkyBean Strato
[366][System][I] HW rev: 22
[372][System][I] FW stm: D0000207


[374][System][I] Starting tasks...
[377][GUI][I] Started
[382][MEMS][I] MEMS started
[385][ESP][I] Started
[382][GNSS][I] Started
[383][System][I] Flight computer init
[394][MEMS][D] ms5611 calibration data for EC
[394][MEMS][D]  C1 40519
[397][MEMS][D]  C2 38603
[401][MEMS][D]  C3 23193
[401][MEMS][D]  C4 23170
[404][MEMS][D]  C5 30350
[408][MEMS][D]  C6 28097
[408][MEMS][E] MS5611 EE not responding
[414][ESP][I] ets Jul 29 2019 12:21:46
[414][ESP][I] 
[416][ESP][I] rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
[421][ESP][I] configsip: 0, SPIWP:0xee
[422][ESP][I] clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
[425][ESP][I] mode:DIO, clock div:1
[437][MEMS][I] ---------------------------------------------------
[438][ESP][I] load:0x3fff0030,len:5072
[438][MEMS][I] ACC sens 4147.000000; 4132.000000; 4011.000000;
[443][ESP][I] load:0x40078000,len:13824
[448][MEMS][I] ACC bias -23.000000; -277.000000; 178.000000;
[449][ESP][I] load:0x40080400,len:3688
[456][ESP][I] entry 0x40080654
[452][MEMS][I] GYR bias 42.400002; -73.800003; -128.199997;
[462][MEMS][I] MAG sens 2478.000000; 2377.000000; 3455.000000;
[463][MEMS][I] MAG bias 1284.000000; 839.000000; -416.000000;
[466][MEMS][I] ---------------------------------------------------
[470][MEMS][I] IMU calibration parameters loaded.
[560][GNSS][D] >>> FNR MSG,1,initialized
[562][GNSS][D] FN: R MSG,1,initialized
[567][GNSS][D] <<< DGV
[573][GNSS][D] >>> DGV build-202008031108
[575][GNSS][D] DG: V build-202008031108
[583][GNSS][D] FANET FW file version is '202008031108'
[585][GNSS][D] FANET module version is '202008031108'
[587][GNSS][I] FANET FW is up to date!
[589][GNSS][D] <<< FNA
[597][GNSS][D] >>> FNA 11,25DF
[600][GNSS][D] FN: A 11,25DF
[602][GNSS][D] <<< FAX
[608][GNSS][D] >>> FAX 122,2,1
[608][GNSS][D] FA: X 122,2,1
[610][GNSS][D] <<< DGP 1
[621][GNSS][D] >>> DGR OK
[622][GNSS][D] DG: R OK
[634][GNSS][I] FANET module ready
[637][GUI][I] reg 00 = 65
[639][GNSS][I] FANET Set type
[642][GUI][I] Controller HX8352
[645][GNSS][D] <<< FNC 1,1,1
[654][GNSS][D] >>> FNR OK
[657][GNSS][D] FN: R OK
[660][GNSS][I] FANET Set Flarm
[660][GNSS][D] <<< FAP 1
[666][GNSS][D] >>> FAR OK
[668][GNSS][D] FA: R OK
[671][GNSS][I] FANET Set mode
[673][GNSS][D] <<< FNM 1
[677][GNSS][D] >>> FNR OK
[680][GNSS][D] FN: R OK
[684][GNSS][D] <<< FNT 2,0,0,0,0,D,4D61726B7573204C756564696E
[694][GNSS][D] >>> FNR OK
[696][GNSS][D] FN: R OK
[1143][GUI][I] GUI ready
[1436][ESP][I] 			boot start 3
[1566][ESP][I] 			pipe_downmix_init
[1572][ESP][I] 			pipe_sound_init
[1574][ESP][I] 			pipe_vario_init
[1586][ESP][I] 			Action command: src_type:131072, source:0x3f810d1c cmd:8, data:0xc, data_len:4
[1605][ESP][I] 			Action command: src_type:131072, source:0x3f810e4c cmd:8, data:0xc, data_len:4
[1608][ESP][I] 			Action command: src_type:131072, source:0x3f810d1c cmd:8, data:0xc, data_len:4
[1624][ESP][I] 			Action command: src_type:131072, source:0x3f810e4c cmd:8, data:0xc, data_len:4
[1670][System][I] PWR 3.82V, -290ma
[1688][ESP][D] 			sending info
[1692][ESP][D] ESP bt: C4:DD:57:7F:27:06
[1698][ESP][D] ESP ap: C4:DD:57:7F:27:05
[1700][ESP][D] ESP sta: C4:DD:57:7F:27:04
[1721][ESP][I] esp_set_bt_mode
[1732][ESP][I] 			boot done 256
[1737][ESP][I] 			bt_set_mode
[2294][ESP][I] 			pipe_bluetooth_init
[2306][ESP][I] W (2053) BT_BTC: A2DP Enable with AVRC
[2318][ESP][I] 			bt_gap_cb event: 10
[2322][ESP][I] 			bt_gap_cb event: 10
[2325][ESP][I] 			bt_gap_cb event: 10
[2401][ESP][I] 			ble_gatts_profile_cb 153
[2405][ESP][I] 			ble_gatts_profile_cb 176
[2407][ESP][I] 			ble_gatts_profile_cb 180
[2414][ESP][I] 			The number handle = 4
[2421][ESP][I] 			bt_gap_cb event: 10
[2423][ESP][I] 			ble_gap_cb event = 19
[2425][ESP][I] 			ble_gatts_profile_cb event = 12
[61682][System][I] PWR 3.79V, -368ma
[120465][ESP][D] 			handle 01 1.562ms
[121692][System][I] PWR 3.79V, -358ma
[131617][ESP][D] 			handle 01 1.226ms
[148084][ESP][D] 			handle 01 1.045ms
[166592][ESP][I] 			ble_gap_cb event = 11
[172227][ESP][E] 			authentication failed, status:0
[175233][ESP][I] W (174971) BT_BTM: btm_sec_clr_temp_auth_service() - no dev CB
[175241][ESP][I] 
[175243][ESP][I] W (174971) BT_APPL: gattc_conn_cb: if=3 st=0 id=3 rsn=0x16
[175338][ESP][I] lld_pdu_get_tx_flush_nb HCI packet count mismatch (0, 1)
[175342][ESP][I] E (175073) BT_BTM: Device not found
[175348][ESP][I] 
[175350][ESP][I] E (175073) BT_APPL: bta_gattc_mark_bg_conn unable to find the bg connection mask for: 4e:6a:49:fe:e8:a7
[181700][System][I] PWR 3.79V, -365ma
[238428][ESP][D] 			handle 01 1.005ms
[240686][GNSS][D] <<< FNT 2,0,0,0,0,D,4D61726B7573204C756564696E
[240700][GNSS][D] >>> FNR OK
[240705][GNSS][D] FN: R OK
[241710][System][I] PWR 3.79V, -367ma
[242238][ESP][D] 			handle 01 1.540ms
[301722][System][I] PWR 3.78V, -400ma
[314433][ESP][D] 			handle 01 2.117ms
[330145][ESP][D] 			handle 01 1.920ms
[361735][System][I] PWR 3.78V, -365ma
[421750][System][I] PWR 3.78V, -420ma
[423354][ESP][D] 			handle 01 1.041ms
[459068][ESP][D] 			handle 01 1.679ms
[480695][GNSS][D] <<< FNT 2,0,0,0,0,D,4D61726B7573204C756564696E
[480704][GNSS][D] >>> FNR OK
[480707][GNSS][D] FN: R OK
[481764][System][I] PWR 3.78V, -365ma
[512765][ESP][D] 			handle 01 1.072ms
[520380][ESP][D] 			handle 01 1.234ms
[520645][ESP][D] 			handle 01 1.591ms
[532562][ESP][D] 			handle 01 1.524ms
[541778][System][I] PWR 3.77V, -400ma
[595893][ESP][D] 			handle 01 1.297ms
[601786][System][I] PWR 3.78V, -367ma
[634640][ESP][D] 			handle 01 1.561ms
[658449][ESP][I] 			ble_gap_cb event = 11
[661790][System][I] PWR 3.77V, -368ma
[666502][ESP][E] 			authentication failed, status:0
[669506][ESP][I] W (669249) BT_BTM: btm_sec_clr_temp_auth_service() - no dev CB
[669513][ESP][I] 
[669516][ESP][I] W (669251) BT_APPL: gattc_conn_cb: if=3 st=0 id=3 rsn=0x16
[669584][ESP][I] lld_pdu_get_tx_flush_nb HCI packet count mismatch (0, 1)
[669591][ESP][I] E (669309) BT_BTM: Device not found
[669593][ESP][I] 
[669596][ESP][I] E (669309) BT_APPL: bta_gattc_mark_bg_conn unable to find the bg connection mask for: 60:e9:ba:a6:d5:ff
[690224][ESP][I] 			ble_gap_cb event = 11
[706415][ESP][E] 			authentication failed, status:0
[709424][ESP][I] W (709167) BT_BTM: btm_sec_clr_temp_auth_service() - no dev CB
[709443][ESP][I] 
[709448][ESP][I] W (709169) BT_APPL: gattc_conn_cb: if=3 st=0 id=3 rsn=0x16
[709590][ESP][I] lld_pdu_get_tx_flush_nb HCI packet count mismatch (0, 1)
[709597][ESP][I] E (709269) BT_BTM: Device not found
[709600][ESP][I] 
[709603][ESP][I] E (709269) BT_APPL: bta_gattc_mark_bg_conn unable to find the bg connection mask for: 60:e9:ba:a6:d5:ff
[720700][GNSS][D] <<< FNT 2,0,0,0,0,D,4D61726B7573204C756564696E
[720722][GNSS][D] >>> FNR OK
[720729][GNSS][D] FN: R OK
[721806][System][I] PWR 3.78V, -375ma
[748093][ESP][I] 			ble_gap_cb event = 11
[748169][ESP][D] 			handle 60 1.242ms
[761812][ESP][E] 			authentication failed, status:0
[764816][ESP][I] W (764561) BT_BTM: btm_sec_clr_temp_auth_service() - no dev CB
[764820][ESP][I] 
[764822][ESP][I] W (764561) BT_APPL: gattc_conn_cb: if=3 st=0 id=3 rsn=0x16
[764979][ESP][I] lld_pdu_get_tx_flush_nb HCI packet count mismatch (0, 1)
[764987][ESP][I] E (764619) BT_BTM: Device not found
[764990][ESP][I] 
[764993][ESP][I] E (764619) BT_APPL: bta_gattc_mark_bg_conn unable to find the bg connection mask for: 60:e9:ba:a6:d5:ff
[781812][System][I] PWR 3.78V, -365ma
[787357][GUI][D] Start power off
[787366][System][I] Starting power off sequence
[787374][GNSS][I] Done
[787375][MEMS][I] Done
[787430][System][I] Tasks stopped
[787434][System][I] Flight computer deinit
[787439][System][I] Writing configuration to config/device.cfg
[787452][System][I] Writing configuration to config/profiles/default.cfg
[787476][System][I] Writing configuration to config/pilots/pilot.cfg
```

**Comment by fhorinek** [comment] 2021-12-21 08:49
please try to unpair all in bluetooth menu on strato and forget strato connection on smartphone

**Comment by vojtechBohman** [comment] 2022-01-07 21:31
Tried again with FW 208. It still doesn't work.
It requires the pin but still exchanges data in the background.

[See the video](https://drive.google.com/file/d/1-C-28DR09AQOrWbvhaKo7E-pl4bK9xc_/view?usp=sharing)

**Comment by fhorinek** [comment] 2022-01-10 18:47
Thank you for the video, looks like that the phone is trying to display generated passcode on strato (ESP_GAP_BLE_PASSKEY_NOTIF_EVT). 

That is the code you need to input. I will add function to display it.
This behavior is strange since the phone should send the request (ESP_GAP_BLE_PASSKEY_REQ_EVT) to match I/O cap of the strato to confirm it.

**Comment by fhorinek** [comment] 2022-01-11 14:59
Can you try this, it should now display the passcode for you
https://strato.skybean.eu/dev_unstable/

**Comment by vojtechBohman** [comment] 2022-01-11 22:23
This version doesn't work. Vario does not start BT at all. A cant see it
even on other phone.

[image: image.png]
[image: image.png]

**Comment by fhorinek** [comment] 2022-01-12 07:06
Yes I did noticed that, that was the reason I deleted the comment after 10 minutes :-).

**Comment by fhorinek** [comment] 2022-01-12 10:23
Please try it now, it should now display the passcode for you
(also the bluetooth will now work)
https://strato.skybean.eu/dev_unstable/

**Comment by vojtechBohman** [comment] 2022-01-15 16:25
I have tested delivered FW. 
After connecting to Strato the code poped up and connection works now. 
I walked and drived little bit.

I got 2 bus faults
![image](https://user-images.githubusercontent.com/82414966/149629349-14945e9c-4233-4bbe-910a-cd8dbb17670e.png)
![image](https://user-images.githubusercontent.com/82414966/149629369-94116f7e-622d-4da9-a8da-0e345aa7bdf1.png)

**Comment by fhorinek** [comment] 2022-01-15 19:07
It is ok, thanks for the report.
The fault is caused by forward gnss, so the workaround is to disable it.
For now, we are trying to locate it.

**Comment by fhorinek** [comment] 2022-01-15 19:08
Closing, I have open issue with the bus fault

**Closed by fhorinek** 2022-01-15 19:08 UTC
Labels: bug, enhancement
