### ISSUE TITLE
Crashes in every flight (FW 261)

### ISSUE THREAD

**Issue by Magortaur** [fhorinek/BB#265] opened 2022-04-12 20:30 UTC
It crashes in every flight with fw 261 (and any other fw before). These reports were created after a wipe.
[crash_report.zip](https://github.com/fhorinek/BB/files/8476338/crash_report.zip)
[crash_report_1.zip](https://github.com/fhorinek/BB/files/8476339/crash_report_1.zip)
[crash_report_2.zip](https://github.com/fhorinek/BB/files/8476340/crash_report_2.zip)

[crash_report.zip](https://github.com/fhorinek/BB/files/8476342/crash_report.zip)
[crash_report_1.zip](https://github.com/fhorinek/BB/files/8476343/crash_report_1.zip)
[crash_report_2.zip](https://github.com/fhorinek/BB/files/8476345/crash_report_2.zip)
[crash_report_3.zip](https://github.com/fhorinek/BB/files/8476346/crash_report_3.zip)

[crash_report.zip](https://github.com/fhorinek/BB/files/8476349/crash_report.zip)
[crash_report_1.zip](https://github.com/fhorinek/BB/files/8476350/crash_report_1.zip)
[crash_report_2.zip](https://github.com/fhorinek/BB/files/8476351/crash_report_2.zip)

**Comment by fhorinek** [comment] 2022-04-21 22:22
Thank you for your time to upload the reports. The cause is the same as in #272.
The bug is fixed in R262

**Closed by fhorinek** 2022-04-21 22:22 UTC
